name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight UTC
  workflow_dispatch: # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate the Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: fctico11
          outputs: |
            github-contribution-grid-snake.svg
            github-contribution-grid-snake-dark.svg?palette=github-dark
      - name: Push to GitHub
        uses: actions/upload-artifact@v3
        with:
          name: snake-animation
          path: github-contribution-grid-snake.svg

  
